// Modal Content Types
export enum ModalContentTypes {
  FORM_CREATE_BOARD = 'FORM_CREATE_BOARD',
  FORM_CREATE_TASK = 'FORM_CREATE_TASK',
  FORM_UPDATE_TASK = 'FORM_UPDATE_TASK',
  FULL_TASK = 'FULL_TASK'
}
